baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
profileImage = "404.png"
background = "fav.png"

[params.about]
enable = true
title = "About Me"
image = "fav.png"
content = """
Hi! I’m Darren, a current student at the University of Pennsylvania pursuing a degree in Computer Science 
in the School of Engineering and Applied Science, with a minor in Mathematics and Statistics. 


I have a passion for leveraging my skills in software development and machine learning to create impactful solutions
particularly in the fields of social science and networks. My background includes full-stack development, 
building open-source tools for research, and applied data science. I am eager to apply my skills in real-world projects and
take advantage of these opportunities to grow and learn in the field of technology. 


Originally from Abington, Pennsylvania, in my free time I enjoy golfing, swimming, and cooking!
"""

[params.about.languages]
enable = true
title = "Languages:"
items = ["JavaScript", "Typescript", "Python", "Java", "OCaml", "R", "SQL"]

[params.about.technologies]
enable = true
title = "Technologies"
items = ["React", "Node.JS", "Spark", "PyTorch", "TensorFlow", "MongoDB", "Docker", "AWS", "Git", "Kafka"]

